wwwwwwwwwwwwwwwwwwwwwwwwwwww
wddddddddddddwwddddddddddddw
wdwwwwdwwwwwdwwdwwwwwdwwwwdw
wdwwwwdwwwwwdwwdwwwwwdwwwwdw
wpwwwwdwwwwwdwwdwwwwwdwwwwpw
wddddddddddddddddddddddddddw
wdwwwwdwwdwwwwwwwwdwwdwwwwdw
wdwwwwdwwdwwwwwwwwdwwdwwwwdw
wddddddwwddddwwddddwwddddddw
wwwwwwdwwwww ww wwwwwdwwwwww
wwwwwwdwwwww ww wwwwwdwwwwww
wwwwwwdww          wwdwwwwww
wwwwwwdww wwwwGwww wwdwwwwww
wwwwwwdww wwwwwwww wwdwwwwww
      d   wwwwwwww   d      
wwwwwwdww wwwwwwww wwdwwwwww
wwwwwwdww wwwwwwww wwdwwwwww
wwwwwwdww          wwdwwwwww
wwwwwwdww wwwwwwww wwdwwwwww
wwwwwwdww wwwwwwww wwdwwwwww
wddddddddddddwwddddddddddddw
wdwwwwdwwwwwdwwdwwwwwdwwwwdw
wdwwwwdwwwwwdwwdwwwwwdwwwwdw
wpddwwdddddddPddddddddwwddpw
wwwdwwdwwdwwwwwwwwdwwdwwdwww
wwwdwwdwwdwwwwwwwwdwwdwwdwww
wddddddwwddddwwddddwwddddddw
wdwwwwwwwwwwdwwdwwwwwwwwwwdw
wdwwwwwwwwwwdwwdwwwwwwwwwwdw
wddddddddddddddddddddddddddw
wwwwwwwwwwwwwwwwwwwwwwwwwwww